# Generated by Django 5.0.6 on 2024-06-25 22:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("catalogue", "0049_rename_productattribute_productoption_and_more"),
        ("wishlist", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="wishlistitem",
            name="wishlist",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="catalogue.wishlist"
            ),
        ),
        migrations.DeleteModel(
            name="Wishlist",
        ),
    ]
