# Generated by Django 5.0.6 on 2025-02-22 00:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("catalogue", "0086_category_subcategory_and_more"),
        ("discount", "0001_initial"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="categoryoffer",
            unique_together={("category", "offer")},
        ),
        migrations.AlterUniqueTogether(
            name="productoffer",
            unique_together={("product", "offer")},
        ),
        migrations.AddIndex(
            model_name="categoryoffer",
            index=models.Index(
                fields=["category", "offer"], name="discount_ca_categor_c84cc4_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="categoryoffer",
            index=models.Index(
                fields=["offer", "category"], name="discount_ca_offer_i_d5fbf6_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="productoffer",
            index=models.Index(
                fields=["product", "offer"], name="discount_pr_product_7f6b30_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="productoffer",
            index=models.Index(
                fields=["offer", "product"], name="discount_pr_offer_i_ed8cfb_idx"
            ),
        ),
    ]
