# Generated by Django 5.0.6 on 2025-02-23 08:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("discount", "0002_alter_categoryoffer_unique_together_and_more"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="offercondition",
            unique_together={("condition_type", "offer")},
        ),
    ]
