# Generated by Django 5.0.6 on 2025-02-23 12:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("discount", "0003_alter_offercondition_unique_together"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="offercondition",
            name="eligible_categories",
        ),
        migrations.RemoveField(
            model_name="offercondition",
            name="eligible_products",
        ),
    ]
