# Generated by Django 5.0.6 on 2025-02-23 12:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("catalogue", "0091_alter_productvariant_sku"),
        ("discount", "0004_remove_offercondition_eligible_categories_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="offercondition",
            name="eligible_categories",
            field=models.ManyToManyField(blank=True, to="catalogue.category"),
        ),
        migrations.AddField(
            model_name="offercondition",
            name="eligible_products",
            field=models.ManyToManyField(blank=True, to="catalogue.product"),
        ),
    ]
