# Generated by Django 5.0.6 on 2025-03-01 20:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("discount", "0005_offercondition_eligible_categories_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="offer",
            name="target",
            field=models.CharField(
                choices=[
                    ("Product", "The offer is applicable to specific products"),
                    ("Order", "Applicable to the customer's order "),
                ],
                max_length=50,
            ),
        ),
        migrations.AlterField(
            model_name="offercondition",
            name="min_order_value",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                help_text="Specify the minimum order amount required for this offer to be applicable",
                max_digits=10,
                null=True,
            ),
        ),
    ]
