# Generated by Django 5.0.6 on 2025-03-03 21:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("discount", "0006_alter_offer_target_and_more"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="categoryoffer",
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name="categoryoffer",
            name="category",
        ),
        migrations.RemoveField(
            model_name="categoryoffer",
            name="condition",
        ),
        migrations.RemoveField(
            model_name="categoryoffer",
            name="offer",
        ),
        migrations.AlterUniqueTogether(
            name="productoffer",
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name="productoffer",
            name="condition",
        ),
        migrations.RemoveField(
            model_name="productoffer",
            name="offer",
        ),
        migrations.RemoveField(
            model_name="productoffer",
            name="product",
        ),
        migrations.RemoveIndex(
            model_name="voucher",
            name="discount_vo_code_038bce_idx",
        ),
        migrations.RemoveIndex(
            model_name="voucher",
            name="discount_vo_valid_f_953ae8_idx",
        ),
        migrations.AddIndex(
            model_name="voucher",
            index=models.Index(
                fields=["code", "valid_to"], name="discount_vo_code_7a1620_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="voucher",
            index=models.Index(
                fields=["offer", "usage_type"], name="discount_vo_offer_i_e54281_idx"
            ),
        ),
        migrations.DeleteModel(
            name="CategoryOffer",
        ),
        migrations.DeleteModel(
            name="ProductOffer",
        ),
    ]
