# Generated by Django 5.0.6 on 2025-03-05 07:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("discount", "0007_alter_categoryoffer_unique_together_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="offer",
            name="max_discount_allowed",
            field=models.DecimalField(decimal_places=2, default=400.0, max_digits=10),
            preserve_default=False,
        ),
    ]
