# Generated by Django 5.0.6 on 2025-03-07 20:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("discount", "0008_offer_max_discount_allowed"),
    ]

    operations = [
        migrations.RenameField(
            model_name="offer",
            old_name="target",
            new_name="applies_to",
        ),
        migrations.AddField(
            model_name="offercondition",
            name="is_active",
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name="voucher",
            name="is_active",
            field=models.BooleanField(default=True),
        ),
    ]
