# Generated by Django 5.0.6 on 2025-03-08 13:59

import django.db.models.manager
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("discount", "0009_rename_target_offer_applies_to_and_more"),
    ]

    operations = [
        migrations.AlterModelManagers(
            name="voucher",
            managers=[
                ("active_objects", django.db.models.manager.Manager()),
            ],
        ),
        migrations.RemoveField(
            model_name="offer",
            name="applies_to",
        ),
        migrations.RemoveField(
            model_name="offercondition",
            name="is_active",
        ),
        migrations.AddField(
            model_name="offer",
            name="offer_type",
            field=models.CharField(
                choices=[
                    ("product", "Product-level offer"),
                    ("order", "Order-level offer"),
                ],
                default="product",
                max_length=50,
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="offer",
            name="discount_type",
            field=models.CharField(
                choices=[
                    (
                        "Percentage discount",
                        "A certain percentage off  product's price",
                    ),
                    ("Fixed discount", "A fixed amount off product's price"),
                ],
                max_length=50,
            ),
        ),
        migrations.AlterField(
            model_name="offercondition",
            name="min_order_value",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                help_text="Specify the minimum spend required for the offer to be applicable",
                max_digits=10,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="voucher",
            name="usage_type",
            field=models.CharField(
                choices=[
                    ("single", "Can only be used once"),
                    ("multiple", "Can be used multiple number of times"),
                    ("once_per_customer", "Can be used once for every customer"),
                ],
                default="single",
                max_length=50,
            ),
        ),
    ]
