# Generated by Django 5.0.6 on 2025-03-08 18:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("discount", "0010_alter_voucher_managers_remove_offer_applies_to_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="offer",
            name="discount_type",
            field=models.CharField(
                choices=[
                    ("percentage", "A certain percentage off product's price"),
                    ("fixed", "A fixed amount off product's price"),
                ],
                max_length=50,
            ),
        ),
        migrations.AlterField(
            model_name="voucher",
            name="usage_type",
            field=models.CharField(
                choices=[
                    ("single", "Single use"),
                    ("multiple", "Multiple use"),
                    ("once_per_customer", "Once for every customer"),
                ],
                default="single",
                max_length=50,
            ),
        ),
    ]
