# Generated by Django 5.0.6 on 2025-03-10 16:34

import django.db.models.manager
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("discount", "0011_alter_offer_discount_type_alter_voucher_usage_type"),
    ]

    operations = [
        migrations.AlterModelManagers(
            name="offer",
            managers=[
                ("active_objects", django.db.models.manager.Manager()),
            ],
        ),
        migrations.RemoveIndex(
            model_name="offer",
            name="discount_of_store_i_3fa8eb_idx",
        ),
        migrations.RemoveIndex(
            model_name="voucher",
            name="discount_vo_code_7a1620_idx",
        ),
        migrations.RemoveIndex(
            model_name="voucher",
            name="discount_vo_offer_i_e54281_idx",
        ),
        migrations.AddIndex(
            model_name="voucher",
            index=models.Index(fields=["code"], name="discount_vo_code_038bce_idx"),
        ),
        migrations.AddIndex(
            model_name="voucher",
            index=models.Index(
                fields=["valid_to", "valid_from"], name="discount_vo_valid_t_ca1c10_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="voucher",
            index=models.Index(fields=["offer"], name="discount_vo_offer_i_1c6d18_idx"),
        ),
    ]
