# Generated by Django 5.0.6 on 2025-03-11 10:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("discount", "0012_alter_offer_managers_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="offer",
            options={"default_manager_name": "objects"},
        ),
        migrations.AlterModelOptions(
            name="voucher",
            options={"default_manager_name": "objects"},
        ),
        migrations.AlterModelManagers(
            name="offer",
            managers=[],
        ),
        migrations.AlterModelManagers(
            name="voucher",
            managers=[],
        ),
        migrations.AlterField(
            model_name="offer",
            name="discount_type",
            field=models.CharField(
                choices=[
                    ("percentage", "Percentage discount"),
                    ("fixed", "Fixed-Amount discount"),
                ],
                max_length=50,
            ),
        ),
    ]
