# Generated by Django 4.1.2 on 2022-10-23 17:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("catalogue", "0005_alter_review_options_alter_review_product"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Review",
        ),
    ]
