# Generated by Django 4.1.2 on 2022-10-24 08:31

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("catalogue", "0010_vendor_product_vendor"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="vendor",
            options={"default_related_name": "products"},
        ),
        migrations.AlterField(
            model_name="vendor",
            name="customer",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL
            ),
        ),
    ]
