# Generated by Django 4.1.2 on 2023-04-09 19:46

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("catalogue", "0017_review_image_url_review_updated"),
    ]

    operations = [
        migrations.AlterField(
            model_name="product",
            name="label",
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name="review",
            name="image_url",
            field=models.URLField(null=True),
        ),
    ]
