# Generated by Django 4.1.2 on 2023-04-10 19:04

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("catalogue", "0019_alter_product_label"),
    ]

    operations = [
        migrations.AddField(
            model_name="review",
            name="rating",
            field=models.IntegerField(
                choices=[
                    (1, "Very Bad"),
                    (2, "Unsatisfied"),
                    (3, "Just There"),
                    (4, "Satisfied"),
                    (5, "Very Satisfied"),
                ],
                default=3,
            ),
        ),
    ]
