# Generated by Django 4.2 on 2024-06-10 09:19

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):
    dependencies = [
        ("catalogue", "0022_rename_stock_product_in_stock_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="discount",
            name="product",
        ),
        migrations.AddField(
            model_name="discount",
            name="created",
            field=models.DateTimeField(
                auto_now_add=True, default=django.utils.timezone.now
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="discount",
            name="updated",
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name="product",
            name="discount",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="catalogue.discount",
            ),
        ),
    ]
