# Generated by Django 4.2 on 2024-06-10 15:34

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("catalogue", "0024_alter_product_discount"),
    ]

    operations = [
        migrations.AddField(
            model_name="discount",
            name="discount_type",
            field=models.CharField(
                choices=[
                    ("order_discount", "Order_discount"),
                    ("product_discount", "Product_discount"),
                ],
                default="product_discount",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="discount",
            name="code",
            field=models.CharField(max_length=20, unique=True),
        ),
        migrations.AlterField(
            model_name="discount",
            name="discount_percentage",
            field=models.PositiveIntegerField(),
        ),
    ]
