# Generated by Django 4.2 on 2024-06-15 15:28

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("catalogue", "0027_product_rating"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="product",
            name="label",
        ),
        migrations.AlterField(
            model_name="product",
            name="name",
            field=models.CharField(db_index=True, max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name="product",
            name="price",
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
        migrations.AlterField(
            model_name="review",
            name="image_url",
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="review",
            name="rating",
            field=models.IntegerField(
                choices=[
                    (1, "Very Bad"),
                    (2, "Unsatisfied"),
                    (3, "Just There"),
                    (4, "Satisfied"),
                    (5, "Very Satisfied"),
                ],
                default=0,
            ),
        ),
    ]
