# Generated by Django 4.2 on 2024-06-15 16:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("catalogue", "0028_remove_product_label_alter_product_name_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="Offer",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=50)),
                (
                    "applied_to",
                    models.CharField(
                        choices=[
                            (
                                "vouchers",
                                "Accessible after a customer enters the vouchers code",
                            ),
                            ("all users", "The offer is applicable to all customers"),
                            (
                                "user based",
                                "Only a certain type of customer is this offer applicable to .e.g. first time buyers",
                            ),
                        ],
                        max_length=50,
                    ),
                ),
                ("valid_from", models.DateTimeField()),
                ("valid_to", models.DateTimeField()),
                (
                    "target",
                    models.CharField(
                        choices=[("Product", "product"), ("Shipping", "shipping")],
                        max_length=50,
                    ),
                ),
                (
                    "discount_type",
                    models.CharField(
                        choices=[
                            ("Free shipping", "Free shipping"),
                            (
                                "Percentage discount",
                                "A certain percentage off of the customer's order/shipping fee",
                            ),
                            (
                                "Fixed discount",
                                "A fixed amount off of the customer's order/shipping fee",
                            ),
                        ],
                        max_length=50,
                    ),
                ),
                (
                    "discount_value",
                    models.DecimalField(decimal_places=2, max_digits=10),
                ),
                (
                    "total_discount_offered",
                    models.DecimalField(decimal_places=2, max_digits=10),
                ),
                (
                    "minimum_order_value",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=10, null=True
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Voucher",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=50)),
                ("description", models.TextField()),
                ("code", models.CharField(max_length=50, unique=True)),
                ("valid_from", models.DateTimeField()),
                ("valid_to", models.DateTimeField()),
                (
                    "usage_type",
                    models.CharField(
                        choices=[
                            ("single", ""),
                            ("multiple", ""),
                            ("one per customer", ""),
                        ],
                        default="one per customer",
                        max_length=50,
                    ),
                ),
                ("max_usage", models.PositiveIntegerField()),
                ("num_of_usage", models.PositiveIntegerField(default=0)),
                (
                    "offer",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="catalogue.offer",
                    ),
                ),
            ],
        ),
    ]
