# Generated by Django 4.2 on 2024-06-15 16:28

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("catalogue", "0029_offer_voucher"),
    ]

    operations = [
        migrations.AddField(
            model_name="offer",
            name="eligible_products",
            field=models.ManyToManyField(to="catalogue.product"),
        ),
    ]
