# Generated by Django 4.2 on 2024-06-15 16:43

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("catalogue", "0030_offer_eligible_products"),
    ]

    operations = [
        migrations.AlterField(
            model_name="offer",
            name="eligible_products",
            field=models.ManyToManyField(blank=True, null=True, to="catalogue.product"),
        ),
        migrations.AlterField(
            model_name="offer",
            name="total_discount_offered",
            field=models.DecimalField(
                blank=True, decimal_places=2, default=0.0, max_digits=10
            ),
        ),
    ]
