# Generated by Django 4.2 on 2024-06-17 11:17

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("catalogue", "0034_alter_voucher_redeemed_by"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="voucher",
            name="redeemed_by",
        ),
        migrations.AlterField(
            model_name="voucher",
            name="num_of_usage",
            field=models.PositiveIntegerField(blank=True, default=0),
        ),
    ]
