# Generated by Django 5.0.6 on 2024-06-18 12:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("catalogue", "0035_remove_voucher_redeemed_by_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="product",
            name="discount",
        ),
        migrations.AddField(
            model_name="redeemedvoucher",
            name="voucher",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="discount.voucher",
            ),
            preserve_default=False,
        ),
    ]
