# Generated by Django 5.0.6 on 2024-06-18 19:24

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("catalogue", "0036_remove_product_discount_redeemedvoucher_voucher"),
    ]

    operations = [
        migrations.RenameField(
            model_name="offer",
            old_name="applied_to",
            new_name="available_to",
        ),
    ]
