# Generated by Django 5.0.6 on 2024-06-19 01:34

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("catalogue", "0037_rename_applied_to_offer_applied_through"),
    ]

    operations = [
        migrations.RenameField(
            model_name="voucher",
            old_name="max_usage",
            new_name="max_usage_limit",
        ),
        migrations.AddField(
            model_name="product",
            name="attributes",
            field=models.JSONField(null=True),
        ),
        migrations.AlterField(
            model_name="offer",
            name="available_to",
            field=models.CharField(
                choices=[
                    ("All customers", "The offer is available to all customers"),
                    (
                        "First time buyers",
                        "First time buyers only can redeem this offer",
                    ),
                    (
                        "Vouchers",
                        "Accessible after a customer enters the vouchers code",
                    ),
                ],
                max_length=50,
            ),
        ),
        migrations.AlterField(
            model_name="offer",
            name="discount_type",
            field=models.CharField(
                choices=[
                    ("Free shipping", "Free shipping"),
                    (
                        "Percentage discount",
                        "A certain percentage off of a product's price/shipping fee",
                    ),
                    (
                        "Fixed discount",
                        "A fixed amount off of a product's price/shipping fee",
                    ),
                ],
                max_length=50,
            ),
        ),
    ]
