# Generated by Django 5.0.6 on 2024-06-19 02:23

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("catalogue", "0038_rename_max_usage_voucher_max_usage_limit_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="offer",
            name="available_to",
            field=models.CharField(
                choices=[
                    ("All customers", "The offer is available to all customers"),
                    (
                        "First time buyers",
                        "First time buyers only can redeem this offer",
                    ),
                    (
                        "Vouchers",
                        "Accessible after a customer enters the vouchers code",
                    ),
                ],
                max_length=50,
                null=True,
            ),
        ),
    ]
