# Generated by Django 5.0.6 on 2024-06-19 19:51

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("catalogue", "0039_alter_offer_available_to"),
    ]

    operations = [
        migrations.CreateModel(
            name="ProductAttribute",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=50)),
                ("value", models.CharField(max_length=50)),
            ],
        ),
        migrations.RemoveField(
            model_name="product",
            name="attributes",
        ),
        migrations.AddField(
            model_name="product",
            name="attributes",
            field=models.ManyToManyField(to="catalogue.productattribute"),
        ),
    ]
