# Generated by Django 5.0.6 on 2024-06-25 11:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("catalogue", "0041_delete_discount"),
        ("stores", "__first__"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="product",
            name="vendor",
        ),
        migrations.AddField(
            model_name="product",
            name="store",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="stores.store",
            ),
        ),
    ]
