# Generated by Django 5.0.6 on 2024-06-25 19:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        (
            "catalogue",
            "0044_remove_product_attributes_productattribute_product_and_more",
        ),
    ]

    operations = [
        migrations.RemoveField(
            model_name="productattribute",
            name="product",
        ),
        migrations.AddField(
            model_name="product",
            name="attributes",
            field=models.ForeignKey(
                default=3,
                on_delete=django.db.models.deletion.CASCADE,
                to="catalogue.productattribute",
            ),
            preserve_default=False,
        ),
    ]
