# Generated by Django 5.0.6 on 2024-06-25 21:10

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("catalogue", "0047_alter_productattribute_product"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="productattribute",
            options={"verbose_name": "attribute"},
        ),
        migrations.AlterField(
            model_name="productattribute",
            name="name",
            field=models.CharField(max_length=100, unique=True),
        ),
        migrations.AlterUniqueTogether(
            name="productattribute",
            unique_together={("name", "value")},
        ),
    ]
