# Generated by Django 5.0.6 on 2024-06-25 22:06

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("catalogue", "0048_alter_productattribute_options_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameModel(
            old_name="ProductAttribute",
            new_name="ProductOption",
        ),
        migrations.AlterUniqueTogether(
            name="productoption",
            unique_together={("product", "name", "value")},
        ),
        migrations.CreateModel(
            name="Wishlist",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created", models.DateTimeField(auto_now_add=True)),
                ("updated", models.DateTimeField(auto_now=True)),
                ("name", models.CharField(max_length=50)),
                (
                    "audience",
                    models.CharField(
                        choices=[
                            ("public", "Anyone can view this wishlist"),
                            ("private", "Only you can view your wishlist"),
                        ],
                        default="private",
                        max_length=50,
                    ),
                ),
                ("note", models.TextField(blank=True, null=True)),
                (
                    "owner",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "unique_together": {("name", "owner")},
            },
        ),
    ]
