# Generated by Django 5.0.6 on 2024-06-26 16:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("catalogue", "0050_wishlistitem"),
    ]

    operations = [
        migrations.AlterField(
            model_name="wishlistitem",
            name="product",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="catalogue.product",
                unique=True,
            ),
        ),
    ]
