# Generated by Django 5.0.6 on 2024-06-26 16:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("catalogue", "0051_alter_wishlistitem_product"),
    ]

    operations = [
        migrations.AlterField(
            model_name="wishlistitem",
            name="product",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="catalogue.product",
            ),
        ),
        migrations.AlterField(
            model_name="wishlistitem",
            name="wishlist",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="items",
                to="catalogue.wishlist",
            ),
        ),
        migrations.AlterUniqueTogether(
            name="wishlistitem",
            unique_together={("wishlist", "product")},
        ),
    ]
