# Generated by Django 5.0.6 on 2024-06-27 20:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("catalogue", "0052_alter_wishlistitem_product_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="ProductAttribute",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100, unique=True)),
            ],
            options={
                "verbose_name": "attribute",
            },
        ),
        migrations.AddField(
            model_name="product",
            name="product_attribute",
            field=models.ManyToManyField(to="catalogue.productattribute"),
        ),
        migrations.CreateModel(
            name="ProductAttributeValue",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("value", models.CharField(max_length=100, unique=True)),
                (
                    "attribute",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="attributes",
                        to="catalogue.productattribute",
                    ),
                ),
            ],
            options={
                "verbose_name": "attribute_value",
                "verbose_name_plural": "attribute_values",
                "unique_together": {("attribute", "value")},
            },
        ),
        migrations.DeleteModel(
            name="ProductOption",
        ),
    ]
