# Generated by Django 5.0.6 on 2024-06-27 20:59

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("catalogue", "0053_productattribute_product_product_attribute_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="product",
            name="product_attribute",
        ),
    ]
