# Generated by Django 5.0.6 on 2024-06-27 21:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("catalogue", "0055_remove_product_product_attribute"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="productattributevalue",
            options={
                "verbose_name": "attribute value",
                "verbose_name_plural": "attribute values",
            },
        ),
        migrations.AddField(
            model_name="product",
            name="product_attribute",
            field=models.ManyToManyField(
                through="catalogue.ProductAttributeValue",
                to="catalogue.productattribute",
            ),
        ),
        migrations.AddField(
            model_name="productattributevalue",
            name="product",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                to="catalogue.product",
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="productattribute",
            name="name",
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name="productattributevalue",
            name="attribute",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="attribute",
                to="catalogue.productattribute",
            ),
        ),
        migrations.AlterField(
            model_name="productattributevalue",
            name="value",
            field=models.CharField(max_length=255, unique=True),
        ),
    ]
