# Generated by Django 5.0.6 on 2024-06-27 21:43

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("catalogue", "0056_alter_productattributevalue_options_and_more"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="productattributevalue",
            unique_together={("value", "attribute")},
        ),
        migrations.AddField(
            model_name="product",
            name="attributes",
            field=models.ManyToManyField(to="catalogue.productattribute"),
        ),
        migrations.RemoveField(
            model_name="productattributevalue",
            name="product",
        ),
    ]
