# Generated by Django 5.0.6 on 2024-06-27 21:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("catalogue", "0058_alter_productattributevalue_unique_together_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="product",
            name="product_attribute",
        ),
        migrations.RemoveField(
            model_name="product",
            name="attributes",
        ),
        migrations.AlterField(
            model_name="productattributevalue",
            name="value",
            field=models.CharField(max_length=255),
        ),
        migrations.AddField(
            model_name="product",
            name="attributes",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="catalogue.productattribute",
            ),
        ),
    ]
