# Generated by Django 5.0.6 on 2024-06-27 22:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("catalogue", "0060_remove_product_attributes_productattribute_product"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="productattribute",
            options={"verbose_name": "product attribute"},
        ),
        migrations.AlterField(
            model_name="productattributevalue",
            name="attribute",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="values",
                to="catalogue.productattribute",
            ),
        ),
        migrations.AlterUniqueTogether(
            name="productattribute",
            unique_together={("product", "name")},
        ),
    ]
