# Generated by Django 5.0.6 on 2024-06-28 22:54

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("catalogue", "0061_alter_productattribute_options_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="productattributevalue",
            name="is_default",
            field=models.BooleanField(default=False),
        ),
    ]
