# Generated by Django 5.0.6 on 2024-06-30 04:27

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("catalogue", "0062_productattributevalue_is_default"),
    ]

    operations = [
        migrations.RenameField(
            model_name="offer",
            old_name="minimum_order_value",
            new_name="min_order_value",
        ),
    ]
