# Generated by Django 5.0.6 on 2024-07-03 19:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("catalogue", "0063_rename_minimum_order_value_offer_min_order_value"),
    ]

    operations = [
        migrations.AddField(
            model_name="productattributevalue",
            name="prdct",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="attrvals",
                to="catalogue.product",
            ),
        ),
    ]
