# Generated by Django 5.0.6 on 2024-07-04 08:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("catalogue", "0064_productattributevalue_prdct"),
        ("stores", "0003_rename_customer_store_owner"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="productattributevalue",
            name="prdct",
        ),
        migrations.AddField(
            model_name="offer",
            name="store",
            field=models.ForeignKey(
                default=2,
                on_delete=django.db.models.deletion.CASCADE,
                to="stores.store",
            ),
        ),
        migrations.AlterField(
            model_name="offer",
            name="eligible_products",
            field=models.ManyToManyField(
                blank=True,
                limit_choices_to={
                    "store": models.ForeignKey(
                        default=2,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="stores.store",
                    )
                },
                to="catalogue.product",
            ),
        ),
        migrations.AlterField(
            model_name="product",
            name="name",
            field=models.CharField(db_index=True, max_length=255, unique=True),
        ),
    ]
