# Generated by Django 5.0.6 on 2024-07-04 09:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("catalogue", "0065_remove_productattributevalue_prdct_offer_store_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="offer",
            name="eligible_products",
            field=models.ManyToManyField(
                blank=True,
                limit_choices_to={"store": models.F("store")},
                to="catalogue.product",
            ),
        ),
        migrations.AlterField(
            model_name="voucher",
            name="offer",
            field=models.ForeignKey(
                limit_choices_to={"available_to": "Vouchers"},
                on_delete=django.db.models.deletion.CASCADE,
                to="catalogue.offer",
            ),
        ),
    ]
