# Generated by Django 5.0.6 on 2024-07-11 15:34

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("catalogue", "0070_offer_created_offer_updated_productimage_created_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="review",
            name="image_url",
        ),
    ]
