# Generated by Django 5.0.6 on 2024-07-11 16:26

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("catalogue", "0071_remove_review_image_url"),
    ]

    operations = [
        migrations.RenameField(
            model_name="review",
            old_name="review",
            new_name="review_text",
        ),
        migrations.AlterField(
            model_name="productimage",
            name="title",
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name="review",
            name="rating",
            field=models.IntegerField(
                choices=[
                    (1, "Very Bad"),
                    (2, "Unsatisfied"),
                    (3, "Just There"),
                    (4, "Satisfied"),
                    (5, "Very Satisfied"),
                ]
            ),
        ),
        migrations.AlterField(
            model_name="reviewimage",
            name="title",
            field=models.CharField(max_length=255, null=True),
        ),
    ]
