# Generated by Django 5.0.6 on 2025-01-07 13:38

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("catalogue", "0073_productmedia_remove_productimage_product_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="wishlistitem",
            name="added_at",
            field=models.DateTimeField(
                auto_now_add=True, default=django.utils.timezone.now
            ),
            preserve_default=False,
        ),
    ]
