# Generated by Django 5.0.6 on 2025-01-07 13:55

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("catalogue", "0074_wishlistitem_added_at"),
    ]

    operations = [
        migrations.RenameField(
            model_name="product",
            old_name="in_stock",
            new_name="stock_level",
        ),
    ]
