# Generated by Django 5.0.6 on 2025-01-12 11:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("catalogue", "0075_rename_in_stock_product_stock_level"),
        ("stores", "0004_store_address"),
    ]

    operations = [
        migrations.CreateModel(
            name="ProductVariant",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created", models.DateTimeField(auto_now_add=True)),
                ("updated", models.DateTimeField(auto_now=True)),
                ("sku", models.CharField(max_length=20, unique=True)),
                (
                    "price_adjustment",
                    models.DecimalField(
                        decimal_places=2,
                        default=0.0,
                        help_text="Amount to add/subtract from the product's base price",
                        max_digits=10,
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                ("stock_level", models.PositiveIntegerField()),
                ("quantity_sold", models.PositiveIntegerField(default=0)),
            ],
            options={
                "ordering": ("-quantity_sold",),
            },
        ),
        migrations.CreateModel(
            name="VariantAttribute",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("value", models.CharField(max_length=255)),
                ("is_default", models.BooleanField(default=False)),
            ],
        ),
        migrations.AlterUniqueTogether(
            name="productattributevalue",
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name="productattributevalue",
            name="attribute",
        ),
        migrations.AlterModelOptions(
            name="product",
            options={"ordering": ["-total_sold", "-rating"]},
        ),
        migrations.RemoveIndex(
            model_name="product",
            name="catalogue_p_categor_9848b4_idx",
        ),
        migrations.RenameField(
            model_name="product",
            old_name="price",
            new_name="base_price",
        ),
        migrations.RenameField(
            model_name="product",
            old_name="stock_level",
            new_name="total_stock_level",
        ),
        migrations.RemoveField(
            model_name="product",
            name="available",
        ),
        migrations.RemoveField(
            model_name="product",
            name="quantity_sold",
        ),
        migrations.AddField(
            model_name="product",
            name="is_available",
            field=models.BooleanField(default=True),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="product",
            name="total_sold",
            field=models.PositiveIntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddIndex(
            model_name="product",
            index=models.Index(
                fields=["category", "is_available"],
                name="catalogue_p_categor_0dea7f_idx",
            ),
        ),
        migrations.AddField(
            model_name="productvariant",
            name="product",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="variants",
                to="catalogue.product",
            ),
        ),
        migrations.AddField(
            model_name="variantattribute",
            name="attribute",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="values",
                to="catalogue.productattribute",
            ),
        ),
        migrations.AddField(
            model_name="variantattribute",
            name="variant",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="variant_attributes",
                to="catalogue.productattribute",
            ),
        ),
        migrations.DeleteModel(
            name="ProductAttributeValue",
        ),
        migrations.AddIndex(
            model_name="productvariant",
            index=models.Index(
                fields=["product", "is_active"], name="catalogue_p_product_24ff11_idx"
            ),
        ),
        migrations.AlterUniqueTogether(
            name="variantattribute",
            unique_together={("variant", "attribute")},
        ),
    ]
