# Generated by Django 5.0.6 on 2025-01-12 11:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("catalogue", "0076_productvariant_variantattribute_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="variantattribute",
            name="variant",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="variant_attributes",
                to="catalogue.productvariant",
            ),
        ),
    ]
