# Generated by Django 5.0.6 on 2025-01-13 20:45

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("catalogue", "0078_alter_productvariant_sku_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="offer",
            old_name="claimed",
            new_name="claimed_by",
        ),
    ]
