# Generated by Django 5.0.6 on 2025-01-14 15:28

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("catalogue", "0079_rename_claimed_offer_claimed_by"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="is_standalone",
            field=models.BooleanField(
                default=True,
                help_text="Does/Will this product have variants that inherits its properties?",
            ),
        ),
    ]
