# Generated by Django 5.0.6 on 2025-01-14 15:39

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("catalogue", "0080_product_is_standalone"),
    ]

    operations = [
        migrations.AlterField(
            model_name="product",
            name="is_available",
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name="product",
            name="total_sold",
            field=models.PositiveIntegerField(default=0),
        ),
    ]
