# Generated by Django 5.0.6 on 2025-01-15 13:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("catalogue", "0081_alter_product_is_available_alter_product_total_sold"),
    ]

    operations = [
        migrations.AlterField(
            model_name="offer",
            name="target",
            field=models.CharField(
                choices=[
                    (
                        "Product",
                        "The offer is applicable to a specific product's price",
                    ),
                    ("Shipping", "Applicable to a product's shipping"),
                    (
                        "Order",
                        "Applicable to the customer's whole order e.g. Offers with MOV",
                    ),
                ],
                max_length=50,
            ),
        ),
    ]
