# Generated by Django 5.0.6 on 2025-01-15 14:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("catalogue", "0082_alter_offer_target"),
        ("stores", "0005_alter_store_followers"),
    ]

    operations = [
        migrations.AlterField(
            model_name="offer",
            name="store",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="stores.store",
            ),
        ),
    ]
