# Generated by Django 5.0.6 on 2025-02-16 00:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("catalogue", "0083_alter_offer_store"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="offer",
            name="claimed_by",
        ),
        migrations.RemoveField(
            model_name="offer",
            name="eligible_products",
        ),
        migrations.RemoveField(
            model_name="offer",
            name="store",
        ),
        migrations.RemoveField(
            model_name="voucher",
            name="offer",
        ),
        migrations.RemoveField(
            model_name="redeemedvoucher",
            name="customer",
        ),
        migrations.RemoveField(
            model_name="redeemedvoucher",
            name="voucher",
        ),
    ]
