# Generated by Django 5.0.6 on 2025-02-16 00:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("catalogue", "0084_remove_offer_claimed_by_and_more"),
        ("customers", "0015_customer_last_purchase_date"),
        ("orders", "0025_remove_orderitem_selected_attrs_order_offer_and_more"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Offer",
        ),
        migrations.DeleteModel(
            name="RedeemedVoucher",
        ),
        migrations.DeleteModel(
            name="Voucher",
        ),
    ]
