# Generated by Django 5.0.6 on 2025-02-21 23:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("catalogue", "0085_delete_offer_delete_redeemedvoucher_delete_voucher"),
    ]

    operations = [
        migrations.AddField(
            model_name="category",
            name="subcategory",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="sub_categories",
                to="catalogue.category",
            ),
        ),
        migrations.AlterField(
            model_name="productvariant",
            name="price_adjustment",
            field=models.DecimalField(
                decimal_places=2,
                default=0.0,
                help_text="Amount to add to the product's base price",
                max_digits=10,
            ),
        ),
        migrations.AlterUniqueTogether(
            name="productvariant",
            unique_together={("sku", "product")},
        ),
    ]
