# Generated by Django 5.0.6 on 2025-02-22 00:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("catalogue", "0087_alter_productvariant_unique_together_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="productvariant",
            name="sku",
            field=models.CharField(db_index=True, max_length=20),
        ),
    ]
