# Generated by Django 5.0.6 on 2025-02-22 20:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("catalogue", "0089_attribute_alter_variantattribute_attribute_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="category",
            name="subcategory",
        ),
        migrations.RemoveField(
            model_name="variantattribute",
            name="is_default",
        ),
        migrations.AddField(
            model_name="productvariant",
            name="is_default",
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name="attribute",
            name="name",
            field=models.CharField(max_length=255, unique=True),
        ),
        migrations.AlterField(
            model_name="productvariant",
            name="sku",
            field=models.CharField(db_index=True, max_length=20, unique=True),
        ),
        migrations.AlterField(
            model_name="variantattribute",
            name="variant",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="attributes",
                to="catalogue.productvariant",
            ),
        ),
        migrations.AlterUniqueTogether(
            name="productvariant",
            unique_together={("sku", "product")},
        ),
        migrations.CreateModel(
            name="ProductAttribute",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(blank=True, max_length=255, null=True)),
                (
                    "attribute",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="catalogue.attribute",
                    ),
                ),
                (
                    "product",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="attributes",
                        to="catalogue.product",
                    ),
                ),
            ],
            options={
                "verbose_name": "product attribute",
                "unique_together": {("product", "name")},
            },
        ),
        migrations.AlterField(
            model_name="variantattribute",
            name="attribute",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="catalogue.productattribute",
            ),
        ),
    ]
