# Generated by Django 5.0.6 on 2025-02-23 08:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("catalogue", "0090_remove_category_subcategory_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="productvariant",
            name="sku",
            field=models.CharField(
                db_index=True, max_length=20, unique=True, verbose_name="SKU"
            ),
        ),
    ]
