# Generated by Django 5.0.6 on 2025-03-05 19:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("catalogue", "0092_voucher_redeemedvoucher"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="redeemedvoucher",
            name="customer",
        ),
        migrations.RemoveField(
            model_name="redeemedvoucher",
            name="voucher",
        ),
        migrations.DeleteModel(
            name="Voucher",
        ),
        migrations.DeleteModel(
            name="RedeemedVoucher",
        ),
    ]
