# Generated by Django 5.0.6 on 2025-03-05 19:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("catalogue", "0093_remove_redeemedvoucher_customer_and_more"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="productattribute",
            unique_together=set(),
        ),
    ]
