# Generated by Django 5.0.6 on 2025-03-05 19:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("catalogue", "0094_alter_productattribute_unique_together"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="variantattribute",
            unique_together=set(),
        ),
    ]
