# Generated by Django 5.0.6 on 2025-03-05 20:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("catalogue", "0095_alter_variantattribute_unique_together"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="productattribute",
            unique_together={("product", "name")},
        ),
        migrations.AlterUniqueTogether(
            name="variantattribute",
            unique_together={("variant", "attribute")},
        ),
    ]
