# Generated by Django 5.0.6 on 2025-03-16 16:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("catalogue", "0098_product_is_active_productmedia_is_active_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="specs",
            field=models.JSONField(blank=True, null=True),
        ),
    ]
