# Generated by Django 5.0.6 on 2025-03-16 20:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("catalogue", "0099_product_specs"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="wishlist",
            options={"default_manager_name": "objects"},
        ),
    ]
