# Generated by Django 5.0.6 on 2025-03-18 18:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("catalogue", "0100_alter_wishlist_options"),
    ]

    operations = [
        migrations.AddField(
            model_name="productvariant",
            name="image",
            field=models.ImageField(blank=True, null=True, upload_to="media/variants"),
        ),
    ]
