# Generated by Django 5.0.6 on 2025-03-23 13:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("catalogue", "0101_productvariant_image"),
    ]

    operations = [
        migrations.AddField(
            model_name="productvariant",
            name="attributes",
            field=models.ManyToManyField(
                through="catalogue.VariantAttribute", to="catalogue.productattribute"
            ),
        ),
        migrations.AlterField(
            model_name="review",
            name="sentiment",
            field=models.CharField(
                blank=True,
                choices=[
                    ("POSITIVE", "Positive sentiment"),
                    ("Neutral", "Neutral sentiment"),
                    ("Negative", "Negative sentiment"),
                ],
                max_length=50,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="review",
            name="sentiment_score",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="variantattribute",
            name="variant",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="catalogue.productvariant",
            ),
        ),
    ]
