# Generated by Django 5.0.6 on 2025-03-23 13:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("catalogue", "0102_productvariant_attributes_alter_review_sentiment_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="productattribute",
            name="attribute",
        ),
        migrations.AddField(
            model_name="attribute",
            name="product_attribute",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="catalogue.productattribute",
                verbose_name="Product-specific attribute",
            ),
        ),
        migrations.AlterField(
            model_name="attribute",
            name="name",
            field=models.CharField(
                blank=True,
                max_length=255,
                null=True,
                unique=True,
                verbose_name="Global attribute",
            ),
        ),
        migrations.AlterField(
            model_name="productattribute",
            name="name",
            field=models.CharField(
                blank=True,
                help_text="Product-specific attribute",
                max_length=255,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="productvariant",
            name="attributes",
            field=models.ManyToManyField(
                through="catalogue.VariantAttribute", to="catalogue.attribute"
            ),
        ),
        migrations.AlterField(
            model_name="variantattribute",
            name="attribute",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="catalogue.attribute"
            ),
        ),
    ]
