# Generated by Django 5.0.6 on 2025-03-23 17:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("catalogue", "0103_remove_productattribute_attribute_and_more"),
        ("stores", "0009_store_is_active"),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name="product",
            name="catalogue_p_categor_0dea7f_idx",
        ),
        migrations.RemoveField(
            model_name="product",
            name="is_available",
        ),
        migrations.AlterField(
            model_name="productvariant",
            name="attributes",
            field=models.ManyToManyField(
                related_name="variant",
                through="catalogue.VariantAttribute",
                to="catalogue.attribute",
            ),
        ),
        migrations.AddIndex(
            model_name="product",
            index=models.Index(
                fields=["category", "is_active"], name="catalogue_p_categor_99a0e6_idx"
            ),
        ),
    ]
