# Generated by Django 5.0.6 on 2025-03-24 22:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("catalogue", "0104_remove_product_catalogue_p_categor_0dea7f_idx_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="attribute",
            name="product_attribute",
            field=models.ForeignKey(
                blank=True,
                help_text="Product-specific attribute",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="catalogue.productattribute",
            ),
        ),
        migrations.AlterField(
            model_name="productattribute",
            name="name",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name="productvariant",
            name="attributes",
            field=models.ManyToManyField(
                through="catalogue.VariantAttribute", to="catalogue.attribute"
            ),
        ),
    ]
