# Generated by Django 5.0.6 on 2025-03-25 13:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("catalogue", "0105_alter_attribute_product_attribute_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="attribute",
            name="product_attribute",
        ),
        migrations.AlterField(
            model_name="attribute",
            name="name",
            field=models.CharField(
                blank=True, max_length=255, unique=True, verbose_name="Global attribute"
            ),
        ),
        migrations.AlterField(
            model_name="productattribute",
            name="name",
            field=models.ForeignKey(
                blank=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="catalogue.attribute",
            ),
        ),
    ]
