# Generated by Django 5.0.6 on 2025-03-25 15:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("catalogue", "0106_remove_attribute_product_attribute_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="attribute",
            name="is_global",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="attribute",
            name="product",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="attributes",
                to="catalogue.product",
            ),
        ),
        migrations.DeleteModel(
            name="ProductAttribute",
        ),
    ]
