# Generated by Django 5.0.6 on 2025-03-26 22:26

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("catalogue", "0107_attribute_is_global_attribute_product_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="product",
            options={"ordering": ["-created", "-total_sold", "-rating"]},
        ),
        migrations.AlterUniqueTogether(
            name="productvariant",
            unique_together=set(),
        ),
        migrations.AddField(
            model_name="review",
            name="is_helpful",
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AlterField(
            model_name="attribute",
            name="name",
            field=models.CharField(max_length=255, unique=True),
        ),
        migrations.AlterField(
            model_name="product",
            name="is_standalone",
            field=models.BooleanField(
                default=True,
                help_text="Whether this product can be sold on its own without variants",
            ),
        ),
        migrations.AlterField(
            model_name="productvariant",
            name="is_default",
            field=models.BooleanField(
                default=False,
                help_text="Automatically created variant for standalone products",
            ),
        ),
        migrations.AlterField(
            model_name="productvariant",
            name="price_adjustment",
            field=models.DecimalField(
                decimal_places=2,
                default=Decimal("0.0"),
                help_text="Additional amount to the product's base price",
                max_digits=10,
            ),
        ),
        migrations.AddConstraint(
            model_name="productvariant",
            constraint=models.UniqueConstraint(
                condition=models.Q(("is_default", True)),
                fields=("product",),
                name="unique_default_variant",
            ),
        ),
        migrations.AddConstraint(
            model_name="productvariant",
            constraint=models.UniqueConstraint(
                fields=("product", "sku"), name="unique_variant_sku_per_product"
            ),
        ),
    ]
