# Generated by Django 5.0.6 on 2025-03-26 22:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("catalogue", "0108_alter_product_options_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="productmedia",
            options={
                "ordering": ["-is_primary", "created"],
                "verbose_name_plural": "product media",
            },
        ),
        migrations.AlterModelOptions(
            name="reviewimage",
            options={"ordering": ["-is_primary", "id"]},
        ),
        migrations.AddField(
            model_name="productmedia",
            name="alt_text",
            field=models.CharField(
                blank=True,
                help_text="Alternative text for media (for accessibility)",
                max_length=255,
            ),
        ),
        migrations.AddField(
            model_name="reviewimage",
            name="alt_text",
            field=models.CharField(
                blank=True,
                help_text="Alternative text for image (for accessibility)",
                max_length=255,
            ),
        ),
        migrations.AlterField(
            model_name="product",
            name="is_standalone",
            field=models.BooleanField(
                default=True,
                help_text="If True, this product can be sold directly as a single item. If False, its acts as a template and only its variants can be sold",
            ),
        ),
        migrations.AlterField(
            model_name="reviewimage",
            name="is_primary",
            field=models.BooleanField(
                default=False, help_text="Set as the main image for this review"
            ),
        ),
        migrations.AlterField(
            model_name="reviewimage",
            name="review",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="images",
                to="catalogue.review",
            ),
        ),
    ]
