# Generated by Django 4.0 on 2022-10-12 21:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0002_alter_customer_managers_alter_customer_date_of_birth_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='address',
            old_name='zip_code',
            new_name='postal_code',
        ),
        migrations.AddField(
            model_name='address',
            name='country',
            field=models.CharField(default='USA', max_length=10),
            preserve_default=False,
        ),
    ]
