# Generated by Django 4.1.2 on 2023-03-28 16:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("customers", "0004_alter_address_country_alter_customer_slug"),
        ("catalogue", "0016_alter_product_label_alter_review_user"),
    ]

    operations = [
        migrations.AddField(
            model_name="customer",
            name="products_bought",
            field=models.ManyToManyField(to="catalogue.product"),
        ),
        migrations.AddField(
            model_name="customer",
            name="total_items_bought",
            field=models.PositiveIntegerField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name="customer",
            name="date_of_birth",
            field=models.DateField(null=True, verbose_name="date of birth"),
        ),
        migrations.AlterField(
            model_name="customer",
            name="email",
            field=models.EmailField(
                db_index=True, max_length=254, unique=True, verbose_name="email address"
            ),
        ),
    ]
