# Generated by Django 4.1.2 on 2023-04-10 09:24

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        (
            "customers",
            "0005_customer_products_bought_customer_total_items_bought_and_more",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="customer",
            name="date_of_birth",
            field=models.DateField(null=True),
        ),
    ]
