# Generated by Django 4.2 on 2024-06-15 16:43

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("customers", "0007_customer_is_vendor"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="address",
            options={"verbose_name_plural": "addresses"},
        ),
    ]
