# Generated by Django 4.2 on 2024-06-17 11:09

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("catalogue", "0034_alter_voucher_redeemed_by"),
        ("customers", "0008_alter_address_options"),
    ]

    operations = [
        migrations.AlterField(
            model_name="customer",
            name="products_bought",
            field=models.ManyToManyField(blank=True, to="catalogue.product"),
        ),
        migrations.AlterField(
            model_name="customer",
            name="total_items_bought",
            field=models.PositiveIntegerField(blank=True, default=0, null=True),
        ),
    ]
