# Generated by Django 5.0.6 on 2024-06-18 12:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        # ("catalogue", "0036_remove_product_discount_redeemedvoucher_voucher"),
        ("customers", "0010_customer_redeemed_vouchers"),
    ]

    operations = [
        migrations.AlterField(
            model_name="customer",
            name="address",
            field=models.OneToOneField(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="customers.address",
            ),
        ),
        migrations.AlterField(
            model_name="customer",
            name="redeemed_vouchers",
            field=models.ManyToManyField(
                blank=True, through="discount.RedeemedVoucher", to="discount.voucher"
            ),
        ),
    ]
