# Generated by Django 5.0.6 on 2024-06-29 18:21

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("customers", "0011_alter_customer_address_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="customer",
            old_name="total_items_bought",
            new_name="products_bought_count",
        ),
    ]
