# Generated by Django 5.0.6 on 2025-01-13 20:19

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("catalogue", "0078_alter_productvariant_sku_and_more"),
        ("customers", "0012_rename_total_items_bought_customer_products_bought_count"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="customer",
            name="products_bought_count",
        ),
        migrations.AlterField(
            model_name="customer",
            name="products_bought",
            field=models.ManyToManyField(blank=True, to="catalogue.productvariant"),
        ),
    ]
