# Generated by Django 5.0.6 on 2025-01-13 20:45

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("customers", "0013_remove_customer_products_bought_count_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="customer",
            name="products_bought_count",
            field=models.PositiveIntegerField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name="customer",
            name="total_units_bought",
            field=models.PositiveIntegerField(blank=True, default=0, null=True),
        ),
    ]
