# Generated by Django 5.0.6 on 2025-02-16 00:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("customers", "0014_customer_products_bought_count_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="customer",
            name="last_purchase_date",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
