# Generated by Django 5.0.6 on 2025-02-16 00:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("customers", "0015_customer_last_purchase_date"),
        ("discount", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="customer",
            name="redeemed_vouchers",
            field=models.ManyToManyField(
                blank=True, through="discount.RedeemedVoucher", to="discount.voucher"
            ),
        ),
    ]
