# Generated by Django 5.0.6 on 2025-03-05 14:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("customers", "0016_alter_customer_redeemed_vouchers"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="customer",
            name="redeemed_vouchers",
        ),
    ]
