# Generated by Django 5.0.6 on 2025-03-05 19:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("customers", "0017_remove_customer_redeemed_vouchers"),
        ("discount", "0008_offer_max_discount_allowed"),
    ]

    operations = [
        migrations.AddField(
            model_name="customer",
            name="redeemed_vouchers",
            field=models.ManyToManyField(
                blank=True, through="discount.RedeemedVoucher", to="discount.voucher"
            ),
        ),
    ]
