# Generated by Django 5.0.6 on 2025-03-24 22:05

import customers.models
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("catalogue", "0105_alter_attribute_product_attribute_and_more"),
        ("customers", "0019_remove_customer_address_address_customer"),
        ("orders", "0043_alter_order_status_orderstatuslog"),
    ]

    operations = [
        migrations.AlterField(
            model_name="customer",
            name="products_bought_count",
            field=models.PositiveIntegerField(
                blank=True,
                default=0,
                help_text="Number of unique products purchased",
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="customer",
            name="total_units_bought",
            field=models.PositiveIntegerField(
                blank=True,
                default=0,
                help_text="Sum of all quantities purchased across all products",
                null=True,
            ),
        ),
        migrations.CreateModel(
            name="PurchaseRecord",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("extra", models.JSONField(default=dict, null=True)),
                ("purchased_at", models.DateTimeField(auto_now_add=True)),
                (
                    "customer",
                    models.ForeignKey(
                        on_delete=models.SET(customers.models.get_sentinel_user),
                        related_name="purchases",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "order",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="orders.order",
                    ),
                ),
                (
                    "product_variant",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="catalogue.productvariant",
                    ),
                ),
            ],
        ),
        # migrations.AlterField(
        #     model_name="customer",
        #     name="products_bought",
        #     field=models.ManyToManyField(
        #         blank=True,
        #         through="customers.PurchaseRecord",
        #         to="catalogue.productvariant",
        #     ),
        # ),
    ]
