# Generated by Django 5.0.6 on 2025-03-24 22:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("customers", "0020_alter_customer_products_bought_count_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="customer",
            name="products_bought",
        ),
    ]
