# Generated by Django 5.0.6 on 2025-03-24 22:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("catalogue", "0105_alter_attribute_product_attribute_and_more"),
        ("customers", "0021_remove_customer_products_bought"),
    ]

    operations = [
        migrations.AddField(
            model_name="customer",
            name="products_bought",
            field=models.ManyToManyField(
                blank=True,
                through="customers.PurchaseRecord",
                to="catalogue.productvariant",
            ),
        ),
    ]
