# Generated by Django 4.1.2 on 2022-11-07 15:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("vendors", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="vendor",
            name="about",
            field=models.TextField(default="I sell phones at cheap rates"),
            preserve_default=False,
        ),
    ]
