# Generated by Django 4.1.2 on 2022-11-07 16:07

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ("vendors", "0002_vendor_about"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="vendor",
            options={},
        ),
        migrations.AddField(
            model_name="vendor",
            name="date_joined",
            field=models.DateTimeField(
                auto_now_add=True, default=django.utils.timezone.now
            ),
            preserve_default=False,
        ),
    ]
