# Generated by Django 4.1.2 on 2023-03-24 15:46

import autoslug.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("vendors", "0003_alter_vendor_options_vendor_date_joined"),
    ]

    operations = [
        migrations.AlterField(
            model_name="vendor",
            name="slug",
            field=autoslug.fields.AutoSlugField(
                always_update=True,
                editable=False,
                populate_from="brand_name",
                unique=True,
            ),
        ),
    ]
