# Generated by Django 4.1.2 on 2023-04-10 09:51

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("vendors", "0005_vendor_is_staff"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="vendor",
            name="is_staff",
        ),
    ]
