# Generated by Django 5.0.6 on 2024-07-04 09:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("customers", "0012_rename_total_items_bought_customer_products_bought_count"),
        ("stores", "0003_rename_customer_store_owner"),
    ]

    operations = [
        migrations.AddField(
            model_name="store",
            name="address",
            field=models.OneToOneField(
                null=True,
                on_delete=django.db.models.deletion.RESTRICT,
                to="customers.address",
            ),
        ),
    ]
