# Generated by Django 5.0.6 on 2025-03-14 20:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("stores", "0005_alter_store_followers"),
    ]

    operations = [
        migrations.RenameField(
            model_name="store",
            old_name="brand_name",
            new_name="name",
        ),
    ]
