# Generated by Django 5.0.6 on 2025-03-16 15:36

import autoslug.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("stores", "0006_rename_brand_name_store_name"),
    ]

    operations = [
        migrations.AlterField(
            model_name="store",
            name="slug",
            field=autoslug.fields.AutoSlugField(
                always_update=True, editable=False, populate_from="name", unique=True
            ),
        ),
    ]
