# Generated by Django 5.0.6 on 2025-03-16 20:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("stores", "0007_alter_store_slug"),
    ]

    operations = [
        migrations.AddField(
            model_name="store",
            name="is_verified",
            field=models.BooleanField(default=False),
        ),
    ]
