# Generated by Django 4.0 on 2022-09-28 22:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0002_alter_customer_managers_alter_customer_date_of_birth_and_more'),
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='address',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.PROTECT, to='customers.address', verbose_name='Shipping address'),
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('unpaid', 'Unpaid'), ('paid', 'Paid'), ('delivered', 'Delivered')], default='unpaid', max_length=10, verbose_name='Order status'),
        ),
    ]
