# Generated by Django 4.0 on 2022-10-12 21:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0003_rename_zip_code_address_postal_code_address_country'),
        ('orders', '0002_alter_order_address_alter_order_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='address',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='customers.address', verbose_name='Shipping address'),
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('paid', 'Paid'), ('unpaid', 'Unpaid'), ('delivered', 'Delivered')], default='unpaid', max_length=10, verbose_name='Order status'),
        ),
    ]
