# Generated by Django 4.1.2 on 2023-03-28 16:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        (
            "customers",
            "0005_customer_products_bought_customer_total_items_bought_and_more",
        ),
        ("orders", "0004_alter_order_address"),
    ]

    operations = [
        migrations.AlterField(
            model_name="order",
            name="address",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="customers.address",
                verbose_name="Shipping address",
            ),
        ),
    ]
