# Generated by Django 4.2 on 2024-06-10 09:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("catalogue", "0022_rename_stock_product_in_stock_and_more"),
        ("orders", "0006_orderitem_shipping_fee"),
    ]

    operations = [
        migrations.RenameField(
            model_name="orderitem",
            old_name="cost_per_item",
            new_name="unit_cost",
        ),
        migrations.AddField(
            model_name="order",
            name="discount",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="catalogue.discount",
            ),
        ),
    ]
