# Generated by Django 4.2 on 2024-06-10 17:14

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("orders", "0007_rename_cost_per_item_orderitem_unit_cost_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="orderitem",
            name="discounted_price",
            field=models.DecimalField(
                blank=True, decimal_places=2, max_digits=6, null=True
            ),
        ),
        migrations.AlterField(
            model_name="orderitem",
            name="unit_cost",
            field=models.DecimalField(decimal_places=2, max_digits=6),
        ),
    ]
