# Generated by Django 4.2 on 2024-06-10 21:08

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("orders", "0008_orderitem_discounted_price_alter_orderitem_unit_cost"),
    ]

    operations = [
        migrations.RenameField(
            model_name="orderitem",
            old_name="unit_cost",
            new_name="unit_price",
        ),
    ]
