# Generated by Django 4.2 on 2024-06-15 15:28

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("orders", "0009_rename_unit_cost_orderitem_unit_price"),
    ]

    operations = [
        migrations.AlterField(
            model_name="order",
            name="status",
            field=models.CharField(
                choices=[
                    ("paid", "Paid"),
                    ("awaiting_payment", "Awaiting Payment"),
                    ("delivered", "Delivered"),
                ],
                default="awaiting_payment",
                max_length=16,
                verbose_name="Order status",
            ),
        ),
        migrations.AlterField(
            model_name="orderitem",
            name="discounted_price",
            field=models.DecimalField(
                blank=True, decimal_places=2, max_digits=10, null=True
            ),
        ),
        migrations.AlterField(
            model_name="orderitem",
            name="unit_price",
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
    ]
