# Generated by Django 5.0.6 on 2024-06-19 20:49

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("orders", "0012_orderitem_offer"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="order",
            name="discount",
        ),
        migrations.AlterField(
            model_name="orderitem",
            name="discounted_price",
            field=models.DecimalField(
                blank=True, decimal_places=2, default=Decimal("0"), max_digits=10
            ),
        ),
    ]
