# Generated by Django 5.0.6 on 2024-06-29 12:28

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("orders", "0015_order_offer"),
    ]

    operations = [
        migrations.AddField(
            model_name="orderitem",
            name="selected_attrs",
            field=models.JSONField(blank=True, null=True),
        ),
    ]
