# Generated by Django 5.0.6 on 2024-06-29 18:21

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("orders", "0016_orderitem_selected_attrs"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="order",
            name="offer",
        ),
        migrations.AddField(
            model_name="orderitem",
            name="discounted_shipping",
            field=models.DecimalField(
                decimal_places=2, default=Decimal("0"), max_digits=10
            ),
        ),
        migrations.AlterField(
            model_name="orderitem",
            name="discounted_price",
            field=models.DecimalField(
                decimal_places=2, default=Decimal("0"), max_digits=10
            ),
        ),
        migrations.AlterField(
            model_name="orderitem",
            name="shipping_fee",
            field=models.DecimalField(decimal_places=2, max_digits=6, null=True),
        ),
    ]
