# Generated by Django 5.0.6 on 2025-01-07 13:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("catalogue", "0074_wishlistitem_added_at"),
        ("orders", "0021_order_orders_orde_created_743fca_idx_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="orderitem",
            name="product",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="catalogue.product",
            ),
        ),
    ]
