# Generated by Django 5.0.6 on 2025-01-14 15:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("catalogue", "0080_product_is_standalone"),
        ("orders", "0023_remove_orderitem_product_orderitem_product_variant"),
    ]

    operations = [
        migrations.AddField(
            model_name="orderitem",
            name="product",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="catalogue.product",
            ),
        ),
    ]
