# Generated by Django 5.0.6 on 2025-02-16 00:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("discount", "0001_initial"),
        ("orders", "0024_orderitem_product"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="orderitem",
            name="selected_attrs",
        ),
        migrations.AddField(
            model_name="order",
            name="offer",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="order_offers",
                to="discount.offer",
            ),
        ),
        migrations.AddField(
            model_name="order",
            name="total_amount",
            field=models.DecimalField(decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name="orderitem",
            name="total_price",
            field=models.DecimalField(
                decimal_places=2,
                help_text="The total price for this order item excl. shipping",
                max_digits=10,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="orderitem",
            name="offer",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="discount.offer",
            ),
        ),
    ]
