# Generated by Django 5.0.6 on 2025-02-22 00:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("catalogue", "0086_category_subcategory_and_more"),
        ("orders", "0025_remove_orderitem_selected_attrs_order_offer_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="order",
            old_name="offer",
            new_name="applied_offer",
        ),
        migrations.RenameField(
            model_name="orderitem",
            old_name="offer",
            new_name="applied_offer",
        ),
        migrations.AlterField(
            model_name="orderitem",
            name="product",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="catalogue.product"
            ),
        ),
        migrations.AlterField(
            model_name="orderitem",
            name="product_variant",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="catalogue.productvariant",
            ),
        ),
    ]
