# Generated by Django 5.0.6 on 2025-02-23 08:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("orders", "0027_alter_order_applied_offer_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="orderitem",
            name="total_price",
        ),
    ]
