# Generated by Django 5.0.6 on 2025-02-23 08:04

import django.db.models.expressions
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("orders", "0028_remove_orderitem_total_price"),
    ]

    operations = [
        migrations.AddField(
            model_name="orderitem",
            name="total_price",
            field=models.GeneratedField(
                db_persist=True,
                expression=models.Case(
                    models.When(
                        discounted_price__isnull=False,
                        then=django.db.models.expressions.CombinedExpression(
                            models.F("unit_price"), "*", models.F("quantity")
                        ),
                    ),
                    default=django.db.models.expressions.CombinedExpression(
                        models.F("unit_price"), "*", models.F("quantity")
                    ),
                ),
                output_field=models.DecimalField(decimal_places=2, max_digits=10),
            ),
        ),
    ]
