# Generated by Django 5.0.6 on 2025-03-01 20:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("orders", "0029_orderitem_total_price"),
    ]

    operations = [
        migrations.RenameField(
            model_name="orderitem",
            old_name="shipping_fee",
            new_name="shipping",
        ),
        migrations.RenameField(
            model_name="orderitem",
            old_name="product_variant",
            new_name="variant",
        ),
    ]
