# Generated by Django 5.0.6 on 2025-03-03 21:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("customers", "0016_alter_customer_redeemed_vouchers"),
        ("orders", "0030_rename_shipping_fee_orderitem_shipping_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="order",
            name="address",
        ),
        migrations.AddField(
            model_name="order",
            name="billing_address",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="customers.address",
            ),
        ),
    ]
