# Generated by Django 5.0.6 on 2025-03-05 07:44

import django.db.models.deletion
import django.db.models.expressions
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("discount", "0008_offer_max_discount_allowed"),
        ("orders", "0031_remove_order_address_order_billing_address"),
    ]

    operations = [
        migrations.RenameField(
            model_name="order",
            old_name="applied_offer",
            new_name="offer",
        ),
        migrations.RenameField(
            model_name="orderitem",
            old_name="applied_offer",
            new_name="offer",
        ),
        # migrations.RemoveField(
        #     model_name="orderitem",
        #     name="discounted_price",
        # ),
        migrations.RemoveField(
            model_name="orderitem",
            name="discounted_shipping",
        ),
        migrations.AddField(
            model_name="order",
            name="discount_amount",
            field=models.DecimalField(
                decimal_places=2, default=Decimal("0.0"), max_digits=10
            ),
        ),
        migrations.AddField(
            model_name="order",
            name="voucher",
            field=models.OneToOneField(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="order_voucher",
                to="discount.voucher",
            ),
        ),
        migrations.AddField(
            model_name="orderitem",
            name="discount_amount",
            field=models.DecimalField(
                decimal_places=2, default=Decimal("0.0"), max_digits=10
            ),
        ),
        # migrations.AlterField(
        #     model_name="orderitem",
        #     name="total_price",
        #     field=models.GeneratedField(
        #         db_persist=True,
        #         expression=django.db.models.expressions.CombinedExpression(
        #             models.F("unit_price"), "*", models.F("quantity")
        #         ),
        #         output_field=models.DecimalField(decimal_places=2, max_digits=10),
        #     ),
        # ),
    ]
