# Generated by Django 5.0.6 on 2025-03-05 19:52

import django.db.models.expressions
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("orders", "0032_rename_applied_offer_order_offer_and_more"),
    ]

    # operations = [
    #     # migrations.RemoveField(
    #     #     model_name="orderitem",
    #     #     name="discounted_price",
    #     # ),
    #     migrations.AlterField(
    #         model_name="orderitem",
    #         name="total_price",
    #         field=models.GeneratedField(
    #             db_persist=True,
    #             expression=django.db.models.expressions.CombinedExpression(
    #                 models.F("unit_price"), "*", models.F("quantity")
    #             ),
    #             output_field=models.DecimalField(decimal_places=2, max_digits=10),
    #         ),
    #     ),
    # ]
