# Generated by Django 5.0.6 on 2025-03-05 19:56

import django.db.models.expressions
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("orders", "0033_remove_orderitem_discounted_price_and_more"),
    ]

    operations = [
        # migrations.RemoveField(
        #     model_name="orderitem",
        #     name="discounted_price",
        # ),
        migrations.RemoveField(
            model_name="orderitem",
            name="total_price",
            # field=models.GeneratedField(
            #     db_persist=True,
            #     expression=django.db.models.expressions.CombinedExpression(
            #         models.F("unit_price"), "*", models.F("quantity")
            #     ),
            #     output_field=models.DecimalField(decimal_places=2, max_digits=10),
            # ),
        ),
    ]
