# Generated by Django 5.0.6 on 2025-03-05 20:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("orders", "0034_remove_orderitem_discounted_price_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="orderitem",
            name="discounted_price",
        ),
    ]
