# Generated by Django 5.0.6 on 2025-03-05 22:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("orders", "0036_orderitem_total_price"),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name="order",
            name="orders_orde_created_743fca_idx",
        ),
        migrations.AlterField(
            model_name="order",
            name="status",
            field=models.CharField(
                choices=[
                    ("paid", "Paid"),
                    ("awaiting_payment", "Awaiting Payment"),
                    ("delivered", "Delivered"),
                    ("cancelled", "Cancelled"),
                ],
                default="awaiting_payment",
                max_length=16,
            ),
        ),
        # migrations.AlterField(
        #     model_name="orderitem",
        #     name="total_price",
        #     field=models.DecimalField(decimal_places=2, editable=False, max_digits=10),
        # ),
        migrations.AlterField(
            model_name="orderitem",
            name="unit_price",
            field=models.DecimalField(decimal_places=2, editable=False, max_digits=10),
        ),
    ]
