# Generated by Django 5.0.6 on 2025-03-05 22:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("orders", "0037_remove_order_orders_orde_created_743fca_idx_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="orderitem",
            name="total_price",
        ),
    ]
