# Generated by Django 5.0.6 on 2025-03-05 22:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("orders", "0038_remove_orderitem_total_price"),
    ]

    operations = [
        migrations.AddField(
            model_name="orderitem",
            name="total_price",
            field=models.DecimalField(
                decimal_places=2, default=0, editable=False, max_digits=10
            ),
            preserve_default=False,
        ),
    ]
