# Generated by Django 5.0.6 on 2025-03-07 20:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("orders", "0039_orderitem_total_price"),
    ]

    operations = [
        migrations.AddField(
            model_name="order",
            name="is_active",
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name="orderitem",
            name="is_active",
            field=models.BooleanField(default=True),
        ),
    ]
