# Generated by Django 5.0.6 on 2025-03-10 18:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("orders", "0040_order_is_active_orderitem_is_active"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="orderitem",
            options={"default_manager_name": "objects"},
        ),
    ]
