# Generated by Django 5.0.6 on 2025-03-25 11:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("orders", "0043_alter_order_status_orderstatuslog"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="orderstatuslog",
            options={"ordering": ["-timestamp"], "verbose_name": "status log"},
        ),
    ]
