# Generated by Django 4.1.2 on 2022-10-24 07:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("products", "0008_product_created_product_updated"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="label",
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
