# Generated by Django 4.1.2 on 2022-11-07 15:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("vendors", "0001_initial"),
        ("products", "0011_alter_vendor_options_alter_vendor_customer"),
    ]

    operations = [
        migrations.AlterField(
            model_name="product",
            name="vendor",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="vendors.vendor",
            ),
        ),
        migrations.DeleteModel(
            name="Vendor",
        ),
    ]
