# Generated by Django 4.1.2 on 2022-11-07 15:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("products", "0012_alter_product_vendor_delete_vendor"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="review",
            options={"get_latest_by": "created"},
        ),
    ]
