# Generated by Django 4.1.2 on 2022-11-23 08:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("products", "0014_product_sold"),
    ]

    operations = [
        migrations.AlterField(
            model_name="product",
            name="sold",
            field=models.PositiveIntegerField(default=0),
        ),
    ]
