# Generated by Django 4.2 on 2023-05-10 15:39

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("products", "0020_review_rating"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="shipping_fee",
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=6),
        ),
    ]
