# Generated by Django 4.2 on 2024-06-12 13:23

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("products", "0026_discount_minimum_order_value_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="rating",
            field=models.FloatField(blank=True, null=True),
        ),
    ]
